export 'movies/movies_providers.dart';
export 'movies/movies_respository_provider.dart';
export 'movies/movies_slide_show_provider.dart';
export 'movies/initial_loading_provider.dart';
export 'movies/movie_info_proverder.dart';
export 'actors/actors_by_movie_provider.dart';
export 'actors/actors_repository_provider.dart';
export 'search/search_movies_provider.dart';
export 'views/views_provider.dart';
